#!/bin/bash

if [ ! -d "KNN" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir KNN
fi

#weights =["uniform","distance"]

for (( c=1; c<=15; c++ ))
do  
   python Activity1-KNN.py 1 0 0 $c > KNN/NroTraining_10-Machine_KNN-Distance_uniform-A$c.txt
done

for (( c=1; c<=15; c++ ))
do  
   python Activity1-KNN.py 1 0 1 $c > KNN/NroTraining_10-Machine_KNN-Distance_distance-A$c.txt
done





## python Activity1-KNN.py 1 0 1 1 > KNN/NroTraining_10-Machine_KNN-B$c.txt

