#!/bin/bash

if [ ! -d "NNS" ]; then
  # Control will enter here if $DIRECTORY doesn't exist.
  mkdir NNS
  mkdir NNS/10
  mkdir NNS/67
fi


t=67

#["lbfgs","sgd","adam"]

#num=$(awk 'BEGIN{for(i=0.001;i<=1.0;i+=0.001)print i}')


num=$(awk 'BEGIN{for(i=1;i<=101;i+=10)print i}')
for n in $num
do
  python Activity1-NNS.py 3 $t 0 $n $n 0.001 > NNS/$t/NroTraining_$t-Machine_NNS-Solver_lbfgs-COA_$n-COB_$n-LRI_0.001.txt
done

num=$(awk 'BEGIN{for(i=1;i<=101;i+=10)print i}')
for n in $num
do
  python Activity1-NNS.py 3 $t 1 $n $n 0.001 > NNS/$t/NroTraining_$t-Machine_NNS-Solver_sgd-COA_$n-COB_$n-LRI_0.001.txt
done

num=$(awk 'BEGIN{for(i=1;i<=101;i+=10)print i}')
for n in $num
do
  python Activity1-NNS.py 3 $t 2 $n $n 0.001 > NNS/$t/NroTraining_$t-Machine_NNS-Solver_adam-COA_$n-COB_$n-LRI_0.001.txt
done
